### ISSUE TITLE
content.opf issues

### ISSUE THREAD

**Issue by acabal** [brew/karl-marx-and-friedrich-engels_the-communist-manifesto#1]
- [x] dc:identifier is wrong; should be `url:https://standardebooks.org/ebooks/karl-marx-friedrich-engels/the-communist-manifesto/samuel-moore`  (make sure to change in colophon too)
- [x] `<dc:description>` should be a full sentence (i.e. a complete clauses) describing the work
- [x] `long-description` must be a several paragraphs of escaped HTML describing the work in detail, including relevant historical framing or background info. Think along the lines of a short Wikipedia entry. See other long-descriptions to get an idea of the kind of HTML required.
- [x] `long-description` contains non-curled quote marks; see `lint` output
- [x] `se:url.vcs.github` should be `https://github.com/standardebooks/karl-marx_friedrich-engels_the-communist-manifesto_samuel-moore` (make sure to change in colophon too)
- [x] Put the `<dc:creator>` tags next to their respective `<meta refines>` tags, not side-by-side
- [x] Missing NACOAF links for everyone; this is the LCCN link in a person's Wikipedia page

**Comment by acabal** [comment]
Sorry, I mistyped the dc:identifier. There should be an underscore between the authors, like so: `url:https://standardebooks.org/ebooks/karl-marx_friedrich-engels/the-communist-manifesto/samuel-moore`

**Comment by brew** [comment]
I couldn't find a NACOAF link for Samuel Moore, so I left it out.
