### ISSUE TITLE
cover.svg issues

### ISSUE THREAD

**Issue by acabal** [brew/karl-marx-and-friedrich-engels_the-communist-manifesto#4]
- [x] Text must be in all caps
- [x] Put authors on individual lines, no "and" (see Lyrical Ballads for an example of this kind of cover: https://github.com/standardebooks/william-wordsworth_lyrical-ballads)
- [x] Remember to run `build-images` again after updating cover and titlepage

**Comment by brew** [comment]
As the title also breaks to a second line, this will have four lines (two for title, two for authors). Should the box be made bigger to keep the padding consistent?

**Comment by acabal** [comment]
Yes; the SVG viewbox *height* must exactly fit the contents plus 50px padding on the top and bottom.  The SVG width is fixed, but also requires 50px padding on the left and right, so if any of the lines run in to that padding then they have to be broken up into more lines.

I don't think we have a 2-line title and 2-line author example for you to follow, so you'll have to do this one for the first time. 

Make sure to follow these rules:

- Title text is 80px tall, so keep that in mind when vertically aligning.
- Margin between separate lines of title text is 20px
- Margin between last title line and first author line is 100px
- Author text is 60px tall
- Margin between separate lines of author text is 20px
- Top and bottom canvas margin are 50px

You can either use a program like Inkscape to help you align things, but after saving you'll have to remove all of Inkscape's crazy cruft that it adds to the SVG. I think the better bet would be to start from a cover like Lyrical Ballads, edit the SVG in a text editor, and do the X-alignment math by hand. It's not especially hard, just a little tricky since X starts at the *top* in SVG, not at the bottom.

**Comment by acabal** [comment]
Sorry, I just realized the comment I left here was meant for `titlepage.svg`, but this issue is about `cover.svg`. My mistake.

Now I see you mean the black box in the  cover. In the case where the title is very long, you can use a smaller font size. See The Narrative of Arthur Gordon Pym of Nantucket for the correct font size and spacing: https://github.com/standardebooks/edgar-allan-poe_the-narrative-of-arthur-gordon-pym-of-nantucket/blob/master/images/cover.svg

I think you can probably combine that smaller font sizing for the title text and the two-author byline used in Lyrical Ballads successfully. If not then let me know and I'll think of some other alternative.

**Comment by brew** [comment]
For cover.svg, I used the small text size from 'narrative of arthur...' for the title, and the two line author size and position from 'Lyrical Ballads'.
