### ISSUE TITLE
chapter-3.xhtml issues

### ISSUE THREAD

**Issue by acabal** [brew/karl-marx-and-friedrich-engels_the-communist-manifesto#9]
- [x] Good work on the subsections, however the `<h3>` tags must follow the same format as the `<h2>` tags; set them in Roman numerals with correct subtitling.
- [x] All `<h#>` tags must go in the ToC, so add these subsections to the ToC too as a new `<ol>` item within the Chapter 3 `<li>` item.

**Comment by brew** [comment]
How should I handle the h4 subtitles, like `<h4>(A) Feudal Socialism</h4>`? Both in the page, and in the toc?

**Comment by acabal** [comment]
All `<h#>` tags must go in the ToC, so add those too, just like the previous ones.

In this case I don't think the `<h4>` tags need to be styled any further within the text, they're OK as-is.
